#pragma once

#include "rat_sprites_def.h"

// ===================================================================
// Sada spritu KLASIK - rucne kreslene ASCII sprity (puvodni sada).
// ===================================================================

// krysa 20x12, beh (dve faze nohou) a skok
SPRITE(SPR_RAT_RUN0,
  "..............kkk...",
  ".............kpppk..",
  "......kkkkkkkkgppk..",
  "p...kkggggggggggggk.",
  ".p.kgggggggggggggggk",
  ".pkgggggggggggggwKgk",
  "kpgggggggggggggggggk",
  ".kggggggggggggggggpk",
  "..kkGGGGGGGGGGGGkkk.",
  "....kGk.....kGk.....",
  "....kk.......kk.....",
  "....................")
SPRITE(SPR_RAT_RUN1,
  "..............kkk...",
  ".............kpppk..",
  "......kkkkkkkkgppk..",
  ".p..kkggggggggggggk.",
  "p..kgggggggggggggggk",
  ".pkgggggggggggggwKgk",
  "kpgggggggggggggggggk",
  ".kggggggggggggggggpk",
  "..kkGGGGGGGGGGGGkkk.",
  "......kGk.kGk.......",
  ".......kk..kk.......",
  "....................")
SPRITE(SPR_RAT_JUMP,
  "..............kkk...",
  ".............kpppk..",
  "......kkkkkkkkgppk..",
  "....kkggggggggggggk.",
  "...kgggggggggggggggk",
  "..kgggggggggggggwKgk",
  ".pkggggggggggggggggk",
  "p.kggggggggggggggpk.",
  "...kkGGGGGGGGGGGkk..",
  "....kGGk...kGGk.....",
  ".....kk.....kk......",
  "....................")

// pavouk 11x9, dve faze nohou
SPRITE(SPR_SPIDER0,
  "..k.....k..",
  "...k...k...",
  "..kkVVVkk..",
  ".k.kVvVk.k.",
  "k..kVVVk..k",
  "...kvVvk...",
  "..k.rkr.k..",
  ".k..kkk..k.",
  "k.........k")
SPRITE(SPR_SPIDER1,
  ".k.......k.",
  "..k.....k..",
  "..kkVVVkk..",
  "k..kVvVk..k",
  ".k.kVVVk.k.",
  "...kvVvk...",
  ".k..rkr..k.",
  "k...kkk...k",
  "...........")

// odpadky k jidlu
SPRITE(SPR_CAN,
  ".kkkkk.",
  "kSsssSk",
  "kssssSk",
  "kSRRRSk",
  "kSRRRSk",
  "kSRRRSk",
  "kssssSk",
  "kSsssSk",
  "kSsssSk",
  ".kkkkk.")
SPRITE(SPR_PEAR,
  "....kb..",
  "...kb...",
  "...kek..",
  "..keeek.",
  "..keeek.",
  ".keeeeek",
  "keeeeeEk",
  "keeeeEEk",
  ".keeEEk.",
  "..kkkk..")
SPRITE(SPR_PAPER,
  "..kkkk..",
  ".kccccck",
  "kcccCcck",
  "kccCcCck",
  "kcCccck.",
  ".kcCcck.",
  "..kkkk..")
SPRITE(SPR_ROLL,
  "..kkkkk..",
  ".kwwwwwk.",
  "kwwkkkwwk",
  "kwkbbbkwk",
  "kwkbbbkwk",
  "kwwkkkwwk",
  ".kwwwwwk.",
  "..kkkkk..")

// prekazky na chodniku
SPRITE(SPR_PIPE_STUB,
  "kkkkkkkkkk",
  "kOoLooooOk",
  "kOoLooooOk",
  "kkkkkkkkkk",
  "..kOLoOk..",
  "..kOLoOk..",
  "..kOLoOk..",
  "..kOLoOk..",
  "..kOLoOk..",
  "..kOLoOk..",
  "..kOLoOk..",
  "..kOLoOk..",
  "..kOLoOk..",
  "..kOLoOk..")
SPRITE(SPR_CRATE,
  "kkkkkkkkkkkk",
  "kHxxxxxxxxHk",
  "kxHxxxxxxHxk",
  "kxxHxxxxHxxk",
  "kxxxHHHHxxxk",
  "kxxxHHHHxxxk",
  "kxxHxxxxHxxk",
  "kxHxxxxxxHxk",
  "kHxxxxxxxxHk",
  "kXXXXXXXXXXk",
  "kkkkkkkkkkkk")
SPRITE(SPR_SLIME,
  "....kkkkkkk.....",
  "..kknnnnnnnkk...",
  ".knnnNnnnnNnnnk.",
  "kNnnnnnnNnnnnnNk",
  "kkkkkkkkkkkkkkkk")

// HUD
SPRITE(SPR_HEART,
  ".kk.kk.",
  "krrkrrk",
  "krrrrrk",
  ".krrrk.",
  "..krk..",
  "...k...")
SPRITE(SPR_HEART_EMPTY,
  ".kk.kk.",
  "kKKkKKk",
  "kKKKKKk",
  ".kKKKk.",
  "..kKk..",
  "...k...")

// ===================================================================
// Doplnek (jako kanal-doplnek.zip v sade ASTRA): klic, bublina a stit,
// kachnicka, snek, kapajici trubka a kapka, proud vody, bedynka.
// ===================================================================

// zlaty klic 12x10
SPRITE(SPR_KEY,
  "..kkkk......",
  ".kIFFIk.....",
  "kIFk.kIk....",
  "kIk...kIkkkk",
  "kIk...kIIIIk",
  "kIFk.kIkkJkk",
  ".kIFIkJ.kJk.",
  "..kkkkJ.kJk.",
  "......kkkkk.",
  "............")

// mydlova bublina 10x10, dve faze (odlesk)
SPRITE(SPR_BUBBLE0,
  "...iiii...",
  "..i....i..",
  ".i..w...i.",
  "i..w.....i",
  "i........i",
  "i........i",
  ".i......i.",
  "..i....i..",
  "...iiii...",
  "..........")

SPRITE(SPR_BUBBLE1,
  "...iiii...",
  "..i....i..",
  ".i......i.",
  "i........i",
  "i........i",
  "i.....w..i",
  ".i...w..i.",
  "..i....i..",
  "...iiii...",
  "..........")

// stit kolem krysy 26x20 (krysa na offsetu 3,4), pruhledny vnitrek
SPRITE(SPR_SHIELD0,
  "........iiiiiiiii.........",
  "......iii.......iii.......",
  "....ii.............ii.....",
  "...ii...............ii....",
  "..ii.................ii...",
  ".ii...................ii..",
  ".i.....................i..",
  "ii.....................ii.",
  "ii.....................ii.",
  "i.......................i.",
  "ii.....................ii.",
  "ii.....................ii.",
  ".i.....................i..",
  ".ii...................ii..",
  "..ii.................ii...",
  "...ii...............ii....",
  "....ii.............ii.....",
  "......iii.......iii.......",
  "........iiiiiiiii.........",
  "..........................")

SPRITE(SPR_SHIELD1,
  "........iiiiiiiii.........",
  "......iii.......iii.......",
  "....ii.............ii.....",
  "...ii...............ii....",
  "..ii.................ii...",
  ".ii...................ii..",
  ".i.....................i..",
  "ii.....................ii.",
  "ii.....................ii.",
  "i.......................i.",
  "ii.....................ii.",
  "ii.....................ii.",
  ".i.....................i..",
  ".ii...................ii..",
  "..ii.................ii...",
  "...ii...............ii....",
  "....ii.............ii.....",
  "......iii.......iii.......",
  "........iiiiiiiii.........",
  "..........................")

// gumova kachnicka 24x14 (plovouci ostruvek, hlava vpravo)
SPRITE(SPR_DUCK0,
  "................kkkk....",
  "...............kyyyyk...",
  "..............kyyKyyk...",
  "..............kyyyyyykk.",
  "..............kyyyyyyook",
  "...............kyyyyykk.",
  "................kyyk....",
  "..kkkkkkkkkkkkkkkyyyk...",
  ".kyyyyyyyyyyyyyyyyyyyk..",
  "kyyyyyyyyyyyyyyyyyyyyyk.",
  "kyyyyyyyyyyyyyyyyyyyyyk.",
  ".kyyyyyyyyyyyyyyyyyyyk..",
  "..kkkkkkkkkkkkkkkkkkk...",
  "........................")

SPRITE(SPR_DUCK1,
  "................kkkk....",
  "...............kyyyyk...",
  "..............kyyKyyk...",
  "..............kyyyyyykk.",
  "..............kyyyyyyook",
  "...............kyyyyykk.",
  "................kyyk....",
  "..kkkkkkkkkkkkkkkyyyk...",
  "kkyyyyyyyyyyyyyyyyyyyk..",
  "kyyyyyyyyyyyyyyyyyyyyyk.",
  "kyyyyyyyyyyyyyyyyyyyyyk.",
  ".kyyyyyyyyyyyyyyyyyyyk..",
  "..kkkkkkkkkkkkkkkkkkk...",
  "........................")

// snek 14x9, dve faze (tykadla)
SPRITE(SPR_SNAIL0,
  "...........k..",
  "...kkkkk..k.k.",
  "..kooOOok.kk..",
  ".koOoooOok.k..",
  ".koOOOooOk.k..",
  ".kooooOoOkkbk.",
  ".kbkOOOOkbbbbk",
  "kbbbbbbbbbbbbk",
  ".kkkkkkkkkkkk.")

SPRITE(SPR_SNAIL1,
  "..........k.k.",
  "...kkkkk...k..",
  "..kooOOok.kk..",
  ".koOoooOok.k..",
  ".koOOOooOk.k..",
  ".kooooOoOkkbk.",
  ".kbkOOOOkbbbbk",
  "kbbbbbbbbbbbbk",
  ".kkkkkkkkkkkk.")

// kapajici trubka 12x12 visi ze stropu, kapka 5x7 (pripravena / blika / pada)
SPRITE(SPR_DRIP_PIPE,
  "kkkkkkkkkkkk",
  "kOooLLooooOk",
  "kkkkkkkkkkkk",
  "..kOoLLooOk.",
  "..kOoLLooOk.",
  "..kOoLLooOk.",
  "..kOoLLooOk.",
  "..kOoLLooOk.",
  "kkkkkkkkkkkk",
  "kOooLLooooOk",
  "kkkkkkkkkkkk",
  ".....kk.....")

SPRITE(SPR_DROP_READY,
  "..k..",
  ".kik.",
  ".kik.",
  "kiwik",
  "kiiYk",
  "kYYYk",
  ".kkk.")

SPRITE(SPR_DROP_FLASH,
  "..k..",
  ".kwk.",
  ".kwk.",
  "kwwwk",
  "kwwik",
  "kiiik",
  ".kkk.")

SPRITE(SPR_DROP_FALL,
  "..k..",
  ".kik.",
  ".kik.",
  "kiwik",
  "kiiYk",
  "kYYYk",
  ".kkk.")

// proud vody: tryska 14x8 na zemi, segment 12x8 (opakuje se svisle), cepice 16x8
SPRITE(SPR_JET_PIPE,
  "..kkkkkkkkkk..",
  "..kOooLLoooOk.",
  "..kkkkkkkkkkk.",
  "....kOoLLoOk..",
  "....kOoLLoOk..",
  "..kkkkkkkkkkk.",
  ".kOoooLLooooOk",
  ".kkkkkkkkkkkkk")

SPRITE(SPR_JET_SEG0,
  "..kiYYYYik..",
  "..kYiYYYYk..",
  "..kYYYYwYk..",
  "..kYYiYYYk..",
  "..kYYYYYik..",
  "..kiYYYYYk..",
  "..kYYwYYYk..",
  "..kYYYYiYk..")

SPRITE(SPR_JET_SEG1,
  "..kYYYYYik..",
  "..kiYYYYYk..",
  "..kYYwYYYk..",
  "..kYYYYiYk..",
  "..kiYYYYik..",
  "..kYiYYYYk..",
  "..kYYYYwYk..",
  "..kYYiYYYk..")

SPRITE(SPR_JET_SEG2,
  "..kYYYYwYk..",
  "..kYYiYYYk..",
  "..kYYYYYik..",
  "..kiYYYYYk..",
  "..kYYwYYYk..",
  "..kYYYYiYk..",
  "..kiYYYYik..",
  "..kYiYYYYk..")

SPRITE(SPR_JET_SEG3,
  "..kYYwYYYk..",
  "..kYYYYiYk..",
  "..kiYYYYik..",
  "..kYiYYYYk..",
  "..kYYYYwYk..",
  "..kYYiYYYk..",
  "..kYYYYYik..",
  "..kiYYYYYk..")

SPRITE(SPR_JET_TOP0,
  "................",
  ".....i..w..i....",
  "...i..iwwi..i...",
  "..i.iwwwwwwi.i..",
  "..iiwwYYYYwwii..",
  "...kiYYYYYYik...",
  "....kYYYYYYk....",
  "....kYYYYYYk....")

SPRITE(SPR_JET_TOP1,
  "................",
  "....w..i...w....",
  "...i.iwwwi.i....",
  "..i.iwwwwwwi..i.",
  "..iiwwYYYYwwii..",
  "...kiYYYYYYik...",
  "....kYYYYYYk....",
  "....kYYYYYYk....")

SPRITE(SPR_JET_TOP2,
  "................",
  ".....i..w..i....",
  "...i..iwwi..i...",
  "..i.iwwwwwwi.i..",
  "..iiwwYYYYwwii..",
  "...kiYYYYYYik...",
  "....kYYYYYYk....",
  "....kYYYYYYk....")

SPRITE(SPR_JET_TOP3,
  "................",
  "....w..i...w....",
  "...i.iwwwi.i....",
  "..i.iwwwwwwi..i.",
  "..iiwwYYYYwwii..",
  "...kiYYYYYYik...",
  "....kYYYYYYk....",
  "....kYYYYYYk....")

// bedynka s odmenou 14x13 zavrena / otevrena (klic ji otevre)
SPRITE(SPR_CHEST_CLOSED,
  "..kkkkkkkkkk..",
  ".kHHHHHHHHHHk.",
  "kHxxxxxxxxxxHk",
  "kXxxxxxxxxxxXk",
  "kkkkkkkkkkkkkk",
  "kXxxxxkIkxxxXk",
  "kXxxxxkIkxxxXk",
  "kXxxxxxkxxxxXk",
  "kXxxxxxxxxxxXk",
  "kXxxxxxxxxxxXk",
  "kXXXXXXXXXXXXk",
  ".kkkkkkkkkkkk.",
  "..............")

SPRITE(SPR_CHEST_OPEN,
  ".kkkkkkkkkkkk.",
  "kHHHHHHHHHHHHk",
  "kHxxxxxxxxxxHk",
  "kkkkkkkkkkkkkk",
  "kIFIFIFIFIFIIk",
  "kXIIIIIIIIIIXk",
  "kXxxxxkkxxxxXk",
  "kXxxxxxxxxxxXk",
  "kXxxxxxxxxxxXk",
  "kXxxxxxxxxxxXk",
  "kXXXXXXXXXXXXk",
  ".kkkkkkkkkkkk.",
  "..............")
